### ISSUE TITLE
Which is the best postgres seneca module to use?

### ISSUE THREAD

**Issue by faceleg** [nherment/seneca-postgresql-store#16]
I see this is a fork of @marianr's work - which is most stable?

Would it be possible to have them merged into the ONE TRUE SENECA POSTGRESQL STORE?

**Comment by brycereynolds** [comment]
+1

I'd love to contribute and considering the additions I see in this branch I'm planning on forking here. @nherment what is the timeline for a PR of this branch or is that not the intention here?

**Comment by nherment** [comment]
As far as I know this one is the latest and more stable.
There is no current plan to merge the two branches the main reasons being:
- this one has been renamed
- we now have a commitment to support this current branch

I agree it's not an ideal solution but the fact that:
- the commits clearly show which branch has the most activity
- I'm unsure about the current usage of @marianr's npm package dependents or branch dependents
- because of support commitments we're probably unwilling to rename this branch back to marianr's original one
- I think in any case we should not delete marianr's branch, just for the sake of historical reasons :)
- And probably most importantly I currently don't have the bandwidth to look into it :/

I'll see if I can add a note to marianr's branch readme file to redirect here, with his approval.

@brycereynolds PRs are absolutely welcome on this branch.

**Comment by faceleg** [comment]
Thanks to the thorough answer!
