### ISSUE TITLE
Defining entities not possible

### ISSUE THREAD

**Issue by kamil-mech** [nherment/seneca-postgresql-store#9]
Store expects manually preloaded tables when being used(e.g. ERROR:  relation "sys_entity" does not exist). This prevents define_sys_entity from creating new entities.

My understanding of what happens in define_sys_entity is that it uses load$ first to check if entity exists before it tries to do save$. In other dbs that causes no problems, because it simply returns empty. In here it throws/returns an error telling it cannot find that entity table, which stops the code from proceeding and actually making that table.

**Comment by nherment** [comment]
@kamil-mech, thanks for opening this issue.

I don't think I understand the issue correctly. You expect this plugin to not throw an error when a load$ is performed on a table that does not exist ?

**Comment by kamil-mech** [comment]
Richards said he will think on how to solve that problem

What I am saying in the issue is that triggering seneca.fail on reading
empty/non-existent entries does not let define_sys_entity do its job and as
a result no entities can be made. I don't know whether the change should
apply to the store itself or to the seneca-basic, but Richard told me to
report the issue on the store so I did.

I believe that store could be more gentle in that matter, so that reading
nothing would return nothing without exploding, just like in other stores

**Comment by nherment** [comment]
I still don't understand. Sorry it's been a long day so I'm a bit slow...

Can you provide both:
- a code example of how the store is currently behaving
- a code example of how you'd like the store to behave if we were to apply the change to the store

**Comment by kamil-mech** [comment]
Apologies for the time it took, I have been very busy lately

I have created a tiny test environment for you to clone and play around. It shows the issue clearly.
https://github.com/kamil-mech/temp-postgresql
The only lines you need to care about are at the bottom of app.js, everything else is just convenience setup.

I may have put the issue itself unclear previously. Let me try explain again:
Plugin seems to be inconsistent with other store plugins. The philosophy of seneca stores seems to be that you should not require code changes when switching from one db to another. However in postgresql you need to take extra action and create tables manually. Also, it fails seneca on any attempts to use non-existent tables, whereas other plugins return nothing and continue to live.

I have inserted mongo plugin into the test environment so that you could easily compare behaviour.

Thank you for cooperation

**Comment by nherment** [comment]
ok I understand now :)

It sounds a bit dangerous to do so though. What you are asking is to ignore missing table errors and continue like nothing happened.

I think it's more a choice about how seneca should manage that as some of the stores are schemaless and and others need the schema to be defined before hands.
Currently, the same issue happens with the MySQL store.

Unless I'm mistaken, you don't need code change to use the postgresql store. Rather, you need to define your schema. Your code stays the same.
Whether an error is reported or not, you will need to define your schema. 
There is a lot of value in using SQL data types and I don't think there is an acceptable way to automatically infer data types and generate the schema on the fly. I think there is also a lot of value into having the DBA getting the best out of their database by thinking about how the data will be used since it directly impacts performance. For example, when saving a string, do you use Text or Varchar ? ShortText, LongText ? Varchar(5) or Varchar(255) ?

Thoughts ?

**Comment by kamil-mech** [comment]
I have spoken with **rjrodger**, he has decided to stay with manual table creation.
You can close the issue now, thank you (:
